[package]
name = "fltk-evented"
version = "0.3.0"
edition = "2021"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
description = "Listener widgets for fltk-rs"
repository = "https://github.com/fltk-rs/fltk-evented"
documentation = "https://docs.rs/fltk-evented"
keywords = ["gui", "widgets", "graphics"]
categories = ["gui"]
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4"
tokio = { version = "1", features = ["rt"], optional = true }
async-std = { version = "1", optional = true }

[features]
default = []
